- name: Create multiple users
  hosts: servers
  become: yes
  tasks:
    - name: Add users
      user:
        name: "{{ item }}"
        state: present
      loop:
        - alice
        - bob
        - charlie
