apiVersion: batch/v1
kind: Job
metadata:
  name: parallel-file-processing
spec:
  parallelism: 5
  completions: 100
  template:
    spec:
      containers:
      - name: file-processor
        image: busybox
        command: ["sh", "-c", "echo Processing file $((1 + $RANDOM % 100))"]
      restartPolicy: Never
#If you want to split work across multiple Pods, you can use parallelism. For example, processing 100 files with 5 Pods
