apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-rolebinding
  namespace: core
subjects:
- kind: ServiceAccount
  name: my-service-account
  namespace: core
roleRef:
  kind: Role
  name: service-role
  apiGroup: rbac.authorization.k8s.io
