deploy-helm:
  image: docker.arvancloud.ir/dtzar/helm-kubectl:latest
  stage: deploy
  variables:
    AGENT_KUBECONTEXT: "devops/example01:k8s-connection"
    K8S_NAMESPACE: "devops"
  before_script:
    - kubectl config use-context "$AGENT_KUBECONTEXT"
    - kubectl get ns "$K8S_NAMESPACE" || kubectl create ns "$K8S_NAMESPACE"
  script:
    - helm repo add bitnami https://charts.bitnami.com/bitnami
    - helm upgrdae  --install mysql-02 bitnami/mysql  -n "$K8S_NAMESPACE" 
  environment:
    name: dev
    kubernetes:
      agent: "devops/example01:k8s-connection"
      namespace: "devops"
  tags:
    - docker-installation-docker
