apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: your-dockerhub-username/node-k8s-probes:1.0
        ports:
        - containerPort: 80
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - /usr/src/app/health-check.sh
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - /usr/src/app/ready-check.sh
          initialDelaySeconds: 5
          periodSeconds: 10
