apiVersion: v1
kind: Pod
metadata:
  name: liveness-http
spec:
  containers:
  - name: my-app
    image: nginx
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5  # Wait 5 seconds before first probe
      periodSeconds: 10       # Check every 10 seconds
      failureThreshold: 3      # After 3 failures, restart the container
      timeoutSeconds: 2        # Wait max 2 seconds for a response
