apiVersion: v1
kind: Pod
metadata:
  name: pod-storage02
spec:
  containers:
    - name: nginx
      image: nginx:1.14
      volumeMounts:
        - name: storage
          mountPath: /data
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: pvc-example
