apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-image-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: private-app
  template:
    metadata:
      labels:
        app: private-app
    spec:
      containers:
        - name: app
          image: myregistry.com/myproject/myapp:latest  # ⬅️ Replace with your actual image
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred  # ⬅️ This must match your secret name
