apiVersion: v1
kind: Pod
metadata:
  name: private-image-test
spec:
  containers:
    - name: app
      image: myregistry.com/myproject/myapp:latest  # Replace with your real image
      ports:
        - containerPort: 8080
  imagePullSecrets:
    - name: regcred  # This should match the name of your secret
