stages:
  - build
  - push
  - deploy


build-job:
  image: docker.arvancloud.ir/docker:latest
  services:
    - docker:24-dind
  stage: build
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: "tcp://docker:2375"
  script:
    echo $DOCKER_HOST
    - docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA .
  tags:
    - docker-dind
  only:
    - main

push-job:
  stage: push
  services:
    - docker:24-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN  $CI_REGISTRY
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA
  tags:
    - docker-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: "tcp://docker:2375"
  only:
    - main

deploy-job:
  stage: deploy
  services:
    - docker:24-dind
  script:
    - docker rm -f $CI_PROJECT_NAME &&  docker run -itd --name $CI_PROJECT_NAME -p 9095:80 $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA
  tags:
    - docker-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: "tcp://docker:2375"
  only:
    - main
