apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: edit-services
  namespace: default
subjects:
- kind: ServiceAccount
  name: sa-name
  namespace: default
roleRef:
  kind: Role
  name: service-editor
  apiGroup: rbac.authorization.k8s.io
