apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: <BASE64_ENCODED_CA_CERT>
    server: https://<KUBERNETES_API_SERVER>
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: api-reader-sa
    namespace: dev
  name: api-reader-context
current-context: api-reader-context
users:
- name: api-reader-sa
  user:
    token: <SERVICE_ACCOUNT_TOKEN>
