apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-reader-role
  namespace: dev
rules:
- apiGroups: [""]   # Core API group
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
