scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets:
          - '192.168.1.101:8080'  # Node 1
          - '192.168.1.102:8080'  # Node 2
          - '192.168.1.103:8080'  # Node 3
