apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: monitoring
spec:
  selector:
    name: cadvisor
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
