apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: nginx01 
  labels:
    app: note-sample-app 
spec:
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  replicas: 6
  selector:
    matchLabels:
      app: note-sample-app
  template:
    metadata:
      labels:
        app: note-sample-app
    spec:
      containers:
      - name: web
        image: nginx:1.21
        ports:
        - containerPort: 80
        startupProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
