- name: Debug Example - Multiple Variables
  hosts: localhost
  vars:
    user_name: "Alice"
    server_ip: "192.168.1.100"
  tasks:
    - name: Print multiple variables
      debug:
        msg:
          - "User: {{ user_name }}"
          - "Server IP: {{ server_ip }}"
